AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - gemfiles/**/*
    - spec/**/*
    - vendor/**/*
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

AbcSize:
  Max: 25

BlockLength:
  Exclude:
    - token_auth.gemspec

Documentation:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 15

ModuleLength:
  Exclude:
    - spec/**/*

OrderedDependencies:
  Exclude:
    - token_auth.gemspec

SpaceInsideStringInterpolation:
  EnforcedStyle: space

StringLiterals:
  EnforcedStyle: double_quotes

HttpPositionalArguments:
  Exclude:
    - spec/**/*
