AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*
    - vendor/**/*
  RunRailsCops: true

AbcSize:
  Max: 25

Documentation:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 15

ModuleLength:
  Exclude:
    - spec/**/*

SpaceInsideStringInterpolation:
  EnforcedStyle: space

StringLiterals:
  EnforcedStyle: double_quotes
