sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.0
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.0-beta
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-5.0-beta
addons:
  postgresql: "9.3"
before_script:
  - bundle exec rake db:create db:migrate
